In [24]:
# Numpy 
import numpy as np


arrayList = [1,2,3,4]
arrayList2 = [5,6,7,8]
array1 = np.array([
    [1,2,3,4], 
    [2,3,4,5],
    [3,4,5,6]
    ])
array2 = np.array([5,6,7,8])
# print(arrayList + arrayList2)
# print(array1 + array2)
# print(array1.shape)
print(array1.ndim)
print(array1[1][0])
print(array2[:3])

2
2
[5 6 7]


In [27]:
print(array1 * array2)
print(np.dot(array1, array2))

[[ 5 12 21 32]
 [10 18 28 40]
 [15 24 35 48]]
[ 70  96 122]


In [7]:
import numpy as np
matriks1 = np.array([
    [1, 2, 3, 4],
    [3, 4, 5, 6]
    ])
matriks2 = np.array(
    [5, 6, 7, 8]
    )
print((matriks1) + (matriks2))
print(np.dot(matriks1, matriks2))

C:\Users\bcamaster\AppData\Local\Temp\ipykernel_32048\1086374383.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matriks1 = np.array([


ValueError: operands could not be broadcast together with shapes (2,) (4,) 