In [1]:
f_name, l_name = input().split()
print(f_name, l_name, sep='_')

Alvina_Krisendi


In [2]:
n, m = list(map(int, input().split()))
print(n+m)

8


In [3]:
def add(a, b):
    return a+b

n, m = list(map(int, input().split()))
print(add(n, m))

11


In [12]:
import numpy 

# Numpy linalg matrix
# a = numpy.array([
#     [1, 9, 3], 
#     [3, 4, 7],
#     [2, 8, 6]
#     ])

# x, y, z = numpy.linalg.solve(a, [1, 2, 3])
# print(x, y, z)

def solve(a, b):
    return numpy.linalg.solve(a, b)

a = numpy.array([
    [1, 1, 1],
    [1, -1, -1],
    [2, 8, 1]
    ])

b = numpy.array([4, -2, 19])

x, y, z = solve(a, b)
print(x, y, z)
print(round(x), round(y), round(z))


1.0000000000000018 1.9999999999999996 1.0000000000000009
1 2 1


In [11]:
a = numpy.array([
    [1, 0, 0],
    [1, 1, 0],
    [2, -3, 1]
    ])
b = numpy.array([
    [1, 1, 1],
    [0, -2, -2],
    [0, 0, -7]
    ])
    
print(numpy.dot(a, b))

[[ 1  1  1]
 [ 1 -1 -1]
 [ 2  8  1]]


In [19]:
import numpy

a = numpy.array([
    [0, 0, 2, 1, 2],
    [0, 1, 0, 2, -1],
    [1, 2, 0, -2, 0],
    [0, 0, 0, -1, 1],
    [0, 1, -1, 1, -1]
])

b = numpy.array([1, 1, -4, -2 , -1])

u, v, w, x, y = numpy.linalg.solve(a, b)
print(u, v, w, x, y)
print(round(u), round(v), round(w), round(x), round(y))

2.0 -2.0 1.0 1.0 -1.0
2 - -2 - 1 - 1 - -1
