In [ ]:
import numpy as np
import os
S = np.array([
    [-30, 10, 20],
    [10, 40, -50],
    [20, -50, -10]
])

v = np.array([1, 0, 0])
print(S, v, sep='\n')
for _ in range(1000):
    z = np.dot(S, v)
    v = z / np.linalg.norm(z)
    # print(np.linalg.norm(z))

print(v)
print(np.linalg.norm(v))

In [ ]:
a = np.array([
    [2, 2, 4],
    [1, 3, 5], 
    [2, 3, 4]
])



# w, v = np.linalg.eig(a)

# print(w)
# print(v)

In [ ]:
import numpy as np

a = np.array([
    [0, 11, -5],
    [-2, 17, -7],
    [-4, 26, -10]
])

v = np.array([1, 1, 1])
temp = 0
counter = 0
while (True):
    before = v
    A_V = np.dot(a, v)
    biggest = np.max(A_V)
    temp = biggest
    print("Iteration {}".format(counter))
    print(A_V)
    A_V = A_V / biggest
    v = A_V
    print(v)
    counter += 1
    if np.linalg.norm(before - v) < 0.0001:
        break

print(temp)

print(np.linalg.eig(a))

In [ ]:
a = np.array([
    [0, 11, -5],
    [-2, 17, -7],
    [-4, 26, -10]
])

v = np.array([1, 1, 1])
# alpha = 4.2
alpha = 100000
alpha = 100
temp = 0
for k in range(10000):
    yK = np.dot(np.linalg.inv(a - alpha * np.identity(3)), v)
    v = yK / np.max(yK)
    temp = np.max(yK)

print(temp)
lamb = 1/ temp + alpha
print(lamb)


In [ ]:
import numpy as np

#Householder

a = np.array([
    [4, -2, 1, -1],
    [-2, 4, -2, 1],
    [1, -2, 4, -2],
    [-1, 1, -2, 4]
])

p, q = np.linalg.qr(a, mode='reduced')
print(p, q, sep='\n\n')
print()
p, q = np.linalg.eig(a)
print(p, q, sep='\n\n')


In [40]:
import numpy as np
import math
a = np.array([
    [4, -2, 1, -1],
    [-2, 4, -2, 1],
    [1, -2, 4, -2],
    [-1, 1, -2, 4]
])

xK = a[0:4, 0]
# print(xK)

eK = np.identity(4)[0]
# print(eK)

u1 = xK + np.linalg.norm(xK) * eK

h1 = np.identity(4) - 2 * np.outer(u1, u1)/np.dot(u1, u1)


# print(np.outer(u1, u1))

a1 = np.dot(h1, a)
print(a1)

    

[[-4.69041576e+00  4.05081361e+00 -2.98481003e+00  2.55840860e+00]
 [-1.52655666e-16  2.60747431e+00 -1.08294145e+00  1.81072875e-01]
 [ 3.81639165e-17 -1.30373715e+00  3.54147073e+00 -1.59053644e+00]
 [ 0.00000000e+00  3.03737154e-01 -1.54147073e+00  3.59053644e+00]]


In [49]:
import numpy as np
import math
a = np.array([
    [4, -2, 1, -1],
    [-2, 4, -2, 1],
    [1, -2, 4, -2],
    [-1, 1, -2, 4]
])

# Tridiagonalization

def tridiagonalize(a):
    n = a.shape[0]
    for k in range(n-2):
        xK = a[k+1:, k]
        eK = np.identity(n)[k+1]
        u1 = xK + np.linalg.norm(xK) * eK
        h1 = np.identity(n) - 2 * np.outer(u1, u1)/np.dot(u1, u1)
        a = np.dot(h1, a)
        a = np.dot(a, h1)
    return a

a = tridiagonalize(a)
print(a)


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [55]:
import numpy as np
a = np.array([
    [4, -2, 1, -1],
    [-2, 4, -2, 1],
    [1, -2, 4, -2],
    [-1, 1, -2, 4]
])

p, q = np.linalg.qr(a, mode='reduced')
print(p, q, sep='\n\n')

# [[-4.69041576e+00  4.05081361e+00 -2.98481003e+00  2.55840860e+00]
#  [-1.52655666e-16  2.60747431e+00 -1.08294145e+00  1.81072875e-01]
#  [ 3.81639165e-17 -1.30373715e+00  3.54147073e+00 -1.59053644e+00]
#  [ 0.00000000e+00  3.03737154e-01 -1.54147073e+00  3.59053644e+00]]

[[-0.85280287 -0.49625825  0.06952269  0.14704292]
 [ 0.42640143 -0.77540351 -0.45991935  0.07352146]
 [-0.21320072  0.38770175 -0.78079332  0.44112877]
 [ 0.21320072 -0.04652421  0.41713616  0.88225755]]

[[-4.69041576  4.05081361 -2.98481003  2.5584086 ]
 [ 0.         -2.93102526  2.69840421 -1.24064561]
 [ 0.          0.         -2.9680842   2.70068923]
 [ 0.          0.          0.          2.57325118]]


In [1]:
import numpy as np

A = np.array([
    [0, 0, -2],
    [1, 2, 1],
    [1, 0, 3]
])

# Print eigen value and eigen vector
E, V = np.linalg.eig(A)
print(E, V, sep='\n\n')

[2. 1. 2.]

[[ 0.         -0.81649658  0.70710678]
 [ 1.          0.40824829  0.        ]
 [ 0.          0.40824829 -0.70710678]]
